# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

#GET http://i1.coinone.co.kr/api/talk/notice/?page=1&searchWord=&searchType=&ordering=-created_at
#Accept: application/json

GET https://www.huobi.co.kr/-/g/open/v1/notice/list?r=534410596
Accept: application/json
Accept-Language: ko-KR

###